export interface AdoptionFormModel {
  lastName: string,
  firstName: string,
  phone: string,
  email: string,
  age: number,
  nrOfPplInHousehold: number,
  childrenInHousehold: boolean,
  ageOfYoungestChild?: string,
  typeOfHouse: string,
  otherDog: boolean,
  otherPet: boolean,
  otherPetDetails?: string,
  nrOfHoursAlone: number,
  nrOfDailyWalks: number,
  wantedSizeSmall: boolean,
  wantedSizeMedium: boolean,
  wantedSizeBig: boolean,
  wantedAgePuppy: boolean,
  wantedAgeYoung: boolean,
  wantedAgeAdult: boolean,
  wantedAgeOld: boolean,
  introduction: string,
}
